### ISSUE TITLE
Selecting Graphics Resolution menu hangs/crashes

### ISSUE THREAD

**Issue by steve6375** [schierlm/usb-modboot#2]
If 'Graphics Resolution' is selected **first** (before setting 'Graphics Mode') then black screen (if UEFI-boot) or crash if MBR-boot (using VBox).

**Comment by schierlm** [comment]
Wow, you are a very dedicated tester :-) Thank you very much for that. 

I assume this bug was fixed in 0b4a1f4bedf165d42c23f64bfbe7e292b4a97686 already (which was after I built the core image for the 0.9 release).

Let me build a new core image later today so you can continue testing with that one :)

**Comment by steve6375** [comment]
It doesn't seem to change resolution either (but may be VBox issue?).

**Comment by schierlm** [comment]
Yes, I can reproduce that resolution does not change in VirtualBox if you are already in graphics mode. It works if you switch back to text mode and to graphics mode again. Will check later if I can find a workaround for this.

Anyway, here is latest core-module.dat, including all fixes so far including your suggestion to use ".inc" files: 
[core-module.dat.zip](https://github.com/schierlm/usb-modboot/files/2407868/core-module.dat.zip)

**Comment by schierlm** [comment]
I did not find a better workaround than to toggle the graphics mode twice after changing the resolution.

Will push in a minute. Latest [core-module.dat](https://github.com/schierlm/usb-modboot/files/2408071/core-module.dat.zip).
